/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * 
 * Arnis Lupiks    * set pages for the project 
 *                 * made backgrounds for the program
 *                 * find code for the introduction talk.
 * 
 * Created on Dec 22, 2011, 1:20:35 PM
 */
package LearningApp;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.sodbeans.phonemic.TextToSpeechFactory;
import org.sodbeans.phonemic.tts.TextToSpeech;
/**
 *
 * @author jonathanmeaney
 */
public class MainFrame extends JFrame {
    private static String introText = "Welcome, secondary student ";
    private String name;
    private String Text;
    private int score;
     
    

      /** Creates new form MainFrame */

    public MainFrame() {
        super("First Window");
        initComponents();
        name = " ";
        Text = " ";
        score = 0;
      
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        gameButton = new javax.swing.JButton();
        learnButton = new javax.swing.JButton();
        LeaderboardButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();
        firstPanel = new javax.swing.JPanel();
        enterNameLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        enterNameField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        BackgroundLabel10 = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        nameLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        AboutUs = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        BackgroundLabel9 = new javax.swing.JLabel();
        logicGamePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nameLabel10 = new javax.swing.JLabel();
        LogicBackground = new javax.swing.JLabel();
        GamePanel = new javax.swing.JPanel();
        nameLabel8 = new javax.swing.JLabel();
        GameLabel = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TruthGameButton = new javax.swing.JButton();
        LogicGameButton = new javax.swing.JButton();
        BackgroundLabel7 = new javax.swing.JLabel();
        learnPanel = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        learnLabel = new javax.swing.JLabel();
        truthTableButton = new javax.swing.JButton();
        logicButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();
        LogicPanel = new javax.swing.JPanel();
        learnLabel5 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        truthGamePanel = new javax.swing.JPanel();
        AC3 = new javax.swing.JTextField();
        DorAC5 = new javax.swing.JTextField();
        AD7 = new javax.swing.JTextField();
        ADandDorAC7 = new javax.swing.JTextField();
        D8 = new javax.swing.JTextField();
        Submitbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ResultsBox = new javax.swing.JLabel();
        truthGameLabel = new javax.swing.JLabel();
        nameLabel9 = new javax.swing.JLabel();
        Game1Label = new javax.swing.JLabel();
        BackgroundLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TruthPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        learnLabel1 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        gameTruthButton = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        pandqButton = new javax.swing.JButton();
        porqButton = new javax.swing.JButton();
        pnotqButton = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        BackgroundLabel2 = new javax.swing.JLabel();
        pandqPanel = new javax.swing.JPanel();
        PandQLabel = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        learnLabel2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackgroundLabel3 = new javax.swing.JLabel();
        porqPanel = new javax.swing.JPanel();
        PorQLabel = new javax.swing.JLabel();
        nameLabel5 = new javax.swing.JLabel();
        learnLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        BackgroundLabel4 = new javax.swing.JLabel();
        pnotqPanel = new javax.swing.JPanel();
        PnotQLabel = new javax.swing.JLabel();
        learnLabel4 = new javax.swing.JLabel();
        nameLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BackgroundLabel5 = new javax.swing.JLabel();
        LeaderboardPanel = new javax.swing.JPanel();
        LeaderboardLabel = new javax.swing.JLabel();
        nameLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        BackgroundLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learning Application");
        setMinimumSize(new java.awt.Dimension(420, 620));
        setResizable(false);

        ButtonPanel.setMaximumSize(new java.awt.Dimension(500, 60));
        ButtonPanel.setPreferredSize(new java.awt.Dimension(350, 57));
        ButtonPanel.setLayout(new java.awt.GridLayout(1, 0));

        backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.setPreferredSize(new java.awt.Dimension(10, 40));
        backButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(backButton);

        homeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/home.png"))); // NOI18N
        homeButton.setText("Home");
        homeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton.setPreferredSize(new java.awt.Dimension(10, 40));
        homeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(homeButton);

        gameButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        gameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/menu.png"))); // NOI18N
        gameButton.setText("Game");
        gameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameButton.setPreferredSize(new java.awt.Dimension(10, 40));
        gameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(gameButton);

        learnButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        learnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/learn.png"))); // NOI18N
        learnButton.setText("Learn");
        learnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        learnButton.setPreferredSize(new java.awt.Dimension(10, 40));
        learnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        learnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(learnButton);

        LeaderboardButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        LeaderboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/help.png"))); // NOI18N
        LeaderboardButton.setText("Leadboard");
        LeaderboardButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LeaderboardButton.setPreferredSize(new java.awt.Dimension(10, 40));
        LeaderboardButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LeaderboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaderboardButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(LeaderboardButton);

        exitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/images123.jpg"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setPreferredSize(new java.awt.Dimension(10, 40));
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(exitButton);

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setMaximumSize(new java.awt.Dimension(500, 700));
        ContentPanel.setLayout(new java.awt.CardLayout());

        firstPanel.setBackground(new java.awt.Color(255, 255, 255));
        firstPanel.setMaximumSize(new java.awt.Dimension(500, 700));
        firstPanel.setLayout(null);

        enterNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        enterNameLabel.setText("Please Enter Your Name:");
        firstPanel.add(enterNameLabel);
        enterNameLabel.setBounds(40, 180, 440, 44);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Welcome");
        firstPanel.add(jLabel10);
        jLabel10.setBounds(55, 10, 110, 40);

        enterNameField.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        enterNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterNameFieldActionPerformed(evt);
            }
        });
        firstPanel.add(enterNameField);
        enterNameField.setBounds(60, 310, 397, 54);

        submitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        firstPanel.add(submitButton);
        submitButton.setBounds(60, 440, 397, 58);

        clearButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        firstPanel.add(clearButton);
        clearButton.setBounds(60, 530, 397, 60);

        BackgroundLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        firstPanel.add(BackgroundLabel10);
        BackgroundLabel10.setBounds(-30, 0, 610, 770);

        ContentPanel.add(firstPanel, "card6");

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setPreferredSize(new java.awt.Dimension(350, 475));
        HomePanel.setLayout(null);

        nameLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(255, 255, 0));
        HomePanel.add(nameLabel2);
        nameLabel2.setBounds(310, 10, 146, 40);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Welcome");
        HomePanel.add(jLabel5);
        jLabel5.setBounds(55, 10, 110, 40);
        HomePanel.add(headingLabel);
        headingLabel.setBounds(166, 818, 139, 0);

        AboutUs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AboutUs.setText("ABOUT US");
        HomePanel.add(AboutUs);
        AboutUs.setBounds(180, 100, 160, 29);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Description");
        HomePanel.add(jLabel37);
        jLabel37.setBounds(40, 160, 150, 17);

        jLabel38.setText("This page is dedicated to explaining what our application is about, who designed it,");
        HomePanel.add(jLabel38);
        jLabel38.setBounds(30, 190, 460, 14);

        jLabel39.setText("a brief description of what the other pages are about and how the app applies");
        HomePanel.add(jLabel39);
        jLabel39.setBounds(30, 210, 460, 14);

        jLabel40.setText("to the subject of the project.");
        HomePanel.add(jLabel40);
        jLabel40.setBounds(30, 230, 180, 14);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Application Developers");
        HomePanel.add(jLabel41);
        jLabel41.setBounds(30, 280, 280, 17);

        jLabel42.setText("Barry McGettigan");
        HomePanel.add(jLabel42);
        jLabel42.setBounds(50, 310, 170, 14);

        jLabel43.setText("Arnis Lupiks");
        HomePanel.add(jLabel43);
        jLabel43.setBounds(50, 330, 140, 14);

        jLabel44.setBackground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Brian Wong");
        HomePanel.add(jLabel44);
        jLabel44.setBounds(50, 350, 130, 14);

        jLabel45.setText("Paul Cuffe");
        HomePanel.add(jLabel45);
        jLabel45.setBounds(50, 370, 100, 14);

        jLabel46.setText("Adam Wade");
        HomePanel.add(jLabel46);
        jLabel46.setBounds(50, 390, 140, 14);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("What our application is about");
        HomePanel.add(jLabel53);
        jLabel53.setBounds(30, 440, 250, 17);

        jLabel54.setText("Our application is a game that helps people learn about technology. We believe that");
        HomePanel.add(jLabel54);
        jLabel54.setBounds(30, 480, 440, 14);

        jLabel12.setText("this is just as good as traditional methods of learning such as studying,");
        HomePanel.add(jLabel12);
        jLabel12.setBounds(30, 500, 390, 14);

        jLabel55.setText("because it can be more appealing to people since it is a game and might be");
        HomePanel.add(jLabel55);
        jLabel55.setBounds(30, 520, 400, 14);

        jLabel56.setText("entertaining to some people. The app is also used to explain how digital circuits work,");
        HomePanel.add(jLabel56);
        jLabel56.setBounds(30, 540, 450, 14);

        jLabel57.setText("how truth tables and logic tables work, as well as promoting to use of technology ");
        HomePanel.add(jLabel57);
        jLabel57.setBounds(30, 560, 440, 14);

        jLabel58.setText("and helping people to become more aware and knowlegable about technology.");
        HomePanel.add(jLabel58);
        jLabel58.setBounds(30, 580, 440, 14);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Other Pages");
        HomePanel.add(jLabel47);
        jLabel47.setBounds(30, 620, 150, 17);

        jLabel28.setText("Main Page -  This is the main page of the application, developed by Arnis");
        HomePanel.add(jLabel28);
        jLabel28.setBounds(30, 650, 400, 14);

        jLabel29.setText("Logic Gates - This page is dedicated to the logic gate game, developed by Barry");
        HomePanel.add(jLabel29);
        jLabel29.setBounds(30, 670, 420, 14);

        jLabel30.setText("Truth Tables - This page is dedicated to the truth table game, developed by Brian");
        HomePanel.add(jLabel30);
        jLabel30.setBounds(30, 690, 450, 14);

        jLabel31.setText("Menu - This page is the menu for the app, developed by Paul(Also did the leaderboard)");
        HomePanel.add(jLabel31);
        jLabel31.setBounds(30, 710, 460, 14);

        jLabel48.setText("About Us - This is the page you're on now!!! developed by Adam");
        HomePanel.add(jLabel48);
        jLabel48.setBounds(30, 730, 370, 14);

        BackgroundLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        HomePanel.add(BackgroundLabel9);
        BackgroundLabel9.setBounds(-30, 0, 590, 770);

        ContentPanel.add(HomePanel, "HomeCard");

        logicGamePanel.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Let's Play");
        logicGamePanel.add(jLabel7);
        jLabel7.setBounds(55, 10, 150, 40);

        nameLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel10.setForeground(new java.awt.Color(255, 255, 0));
        logicGamePanel.add(nameLabel10);
        nameLabel10.setBounds(300, 10, 146, 40);

        LogicBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/game logic.jpg"))); // NOI18N
        logicGamePanel.add(LogicBackground);
        LogicBackground.setBounds(-30, -10, 680, 790);

        ContentPanel.add(logicGamePanel, "logicGameCard");

        GamePanel.setBackground(new java.awt.Color(255, 255, 255));
        GamePanel.setLayout(null);

        nameLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel8.setForeground(new java.awt.Color(255, 255, 0));
        GamePanel.add(nameLabel8);
        nameLabel8.setBounds(300, 10, 150, 40);

        GameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        GameLabel.setForeground(new java.awt.Color(255, 255, 0));
        GameLabel.setText("Let's Play");
        GamePanel.add(GameLabel);
        GameLabel.setBounds(50, 10, 111, 40);

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel35.setText("This is the selection screen for you to choose between our games. ");
        GamePanel.add(jLabel35);
        jLabel35.setBounds(10, 170, 490, 21);

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 17)); // NOI18N
        jLabel13.setText("Please choose one.");
        GamePanel.add(jLabel13);
        jLabel13.setBounds(180, 210, 180, 24);

        TruthGameButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        TruthGameButton.setText("Truth Tables");
        TruthGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruthGameButtonActionPerformed(evt);
            }
        });
        GamePanel.add(TruthGameButton);
        TruthGameButton.setBounds(140, 320, 240, 80);

        LogicGameButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        LogicGameButton.setText("Logic");
        LogicGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogicGameButtonActionPerformed(evt);
            }
        });
        GamePanel.add(LogicGameButton);
        LogicGameButton.setBounds(140, 430, 240, 80);

        BackgroundLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        GamePanel.add(BackgroundLabel7);
        BackgroundLabel7.setBounds(-30, 0, 590, 770);

        ContentPanel.add(GamePanel, "GameCard");

        learnPanel.setBackground(new java.awt.Color(255, 255, 255));
        learnPanel.setLayout(null);

        jLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel.setText(" Please select one of the topics which you want to studie:");
        learnPanel.add(jLabel);
        jLabel.setBounds(20, 170, 480, 70);

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 0));
        learnPanel.add(nameLabel);
        nameLabel.setBounds(300, 10, 150, 40);

        learnLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        learnLabel.setForeground(new java.awt.Color(255, 255, 0));
        learnLabel.setText("Let's Learn");
        learnPanel.add(learnLabel);
        learnLabel.setBounds(40, 10, 127, 40);

        truthTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        truthTableButton.setText("Truth Tables");
        truthTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truthTableButtonActionPerformed(evt);
            }
        });
        learnPanel.add(truthTableButton);
        truthTableButton.setBounds(140, 320, 240, 80);

        logicButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        logicButton.setText("Logic");
        logicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicButtonActionPerformed(evt);
            }
        });
        learnPanel.add(logicButton);
        logicButton.setBounds(140, 430, 240, 80);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        learnPanel.add(BackgroundLabel);
        BackgroundLabel.setBounds(-30, 0, 600, 770);

        ContentPanel.add(learnPanel, "LearnCard");

        LogicPanel.setLayout(null);

        learnLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        learnLabel5.setForeground(new java.awt.Color(255, 255, 0));
        learnLabel5.setText("Let's Learn");
        LogicPanel.add(learnLabel5);
        learnLabel5.setBounds(50, 10, 127, 40);

        nameLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(255, 255, 0));
        LogicPanel.add(nameLabel1);
        nameLabel1.setBounds(300, 10, 150, 40);

        jTextField5.setBackground(new java.awt.Color(51, 153, 255));
        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 102));
        jTextField5.setText("Try our Logic game!!");
        LogicPanel.add(jTextField5);
        jTextField5.setBounds(50, 550, 180, 27);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Game");
        jButton2.setPreferredSize(new java.awt.Dimension(75, 27));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        LogicPanel.add(jButton2);
        jButton2.setBounds(50, 600, 170, 60);

        jList2.setBackground(new java.awt.Color(51, 153, 255));
        jList2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 152));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "www.Maths.com", "www.TruthTables.ie", "www.Logic.com", "www.NCIRL.ie" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        LogicPanel.add(jScrollPane5);
        jScrollPane5.setBounds(310, 590, 140, 120);

        jTextField6.setBackground(new java.awt.Color(51, 153, 255));
        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 152));
        jTextField6.setText("Online Resources:");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        LogicPanel.add(jTextField6);
        jTextField6.setBounds(310, 550, 140, 27);

        jTextArea2.setBackground(new java.awt.Color(51, 153, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 102));
        jTextArea2.setRows(5);
        jTextArea2.setText("Logic (from the Greek λογική logikē) is the philosophical study of valid\nreasoning. Logic is used in most intellectual activities, but is studied\nprimarily in the disciplines of philosophy, mathematics, semantics, and \ncomputer science. It examines general forms which arguments may\ntake, which forms are valid, and which are fallacies. In philosophy,\nthe study of logic is applied in most major areas: metaphysics, \nontology, epistemology, and ethics. In mathematics, it is the study of\nvalid inferences within some formal language. Logic is also studied\nin argumentation theory. Logic was studied in several ancient \ncivilizations, including India, China and Greece.\nIn the West, logic was established as a formal discipline by Aristotle,\nwho gave it a fundamental place in philosophy. The study of logic\nwas part of the classical trivium, which also included grammar and\nrhetoric. Logic is often divided into three parts, inductive reasoning,\nabductive reasoning, and deductive reasoning.\n");
        jScrollPane4.setViewportView(jTextArea2);

        LogicPanel.add(jScrollPane4);
        jScrollPane4.setBounds(20, 110, 480, 380);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        LogicPanel.add(jLabel36);
        jLabel36.setBounds(-30, -10, 670, 790);

        ContentPanel.add(LogicPanel, "logicCard");

        truthGamePanel.setLayout(null);
        truthGamePanel.add(AC3);
        AC3.setBounds(220, 300, 40, 40);
        truthGamePanel.add(DorAC5);
        DorAC5.setBounds(270, 380, 40, 30);
        truthGamePanel.add(AD7);
        AD7.setBounds(190, 450, 30, 30);
        truthGamePanel.add(ADandDorAC7);
        ADandDorAC7.setBounds(360, 450, 30, 30);

        D8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D8ActionPerformed(evt);
            }
        });
        truthGamePanel.add(D8);
        D8.setBounds(150, 490, 30, 30);

        Submitbtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Submitbtn.setText("Submit");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        truthGamePanel.add(Submitbtn);
        Submitbtn.setBounds(270, 630, 80, 40);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        truthGamePanel.add(jButton1);
        jButton1.setBounds(140, 630, 80, 40);

        ResultsBox.setForeground(new java.awt.Color(255, 255, 255));
        ResultsBox.setText(" Using the knowlege you learned in the last page, try solve the following truth table:");
        truthGamePanel.add(ResultsBox);
        ResultsBox.setBounds(40, 560, 440, 60);

        truthGameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Truth Page 1.png"))); // NOI18N
        truthGamePanel.add(truthGameLabel);
        truthGameLabel.setBounds(40, 90, 420, 610);

        nameLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel9.setForeground(new java.awt.Color(255, 255, 0));
        truthGamePanel.add(nameLabel9);
        nameLabel9.setBounds(300, 10, 150, 40);

        Game1Label.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Game1Label.setForeground(new java.awt.Color(255, 255, 0));
        Game1Label.setText("True of False?");
        truthGamePanel.add(Game1Label);
        Game1Label.setBounds(40, 10, 180, 40);

        BackgroundLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        truthGamePanel.add(BackgroundLabel8);
        BackgroundLabel8.setBounds(-30, 0, 660, 770);

        jLabel3.setText("jLabel3");
        truthGamePanel.add(jLabel3);
        jLabel3.setBounds(90, 570, 310, 14);

        ContentPanel.add(truthGamePanel, "truthGameCard");

        TruthPanel.setBackground(new java.awt.Color(255, 255, 255));
        TruthPanel.setLayout(null);

        jTextArea1.setBackground(new java.awt.Color(51, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("A truth table is a mathematical table used in logic—specifically in connection with Boolean algebra, boolean functions, and propositional calculus—to compute the functional values of logical expressions on each of their functional arguments, that is, on each combination of values taken by their logical variables.\nIn particular, truth tables can be used to tell whether a propositional expression is true for all legitimate input values, that is, logically valid. \nPractically, a truth table is composed of one column for each input variable (for example, A and B), and one final column for all of the possible results of the logical operation that the table is meant to represent (for example, A XOR B). Each row of the truth table  therefore contains one possible configuration of the input variables   (for instance, A=true B=false), and    the resultof the operation for those   values. Seethe examples below for    further clarification. \n");
        jScrollPane2.setViewportView(jTextArea1);

        TruthPanel.add(jScrollPane2);
        jScrollPane2.setBounds(20, 100, 310, 560);

        learnLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        learnLabel1.setForeground(new java.awt.Color(255, 255, 0));
        learnLabel1.setText("Let's Learn Truth Tables");
        TruthPanel.add(learnLabel1);
        learnLabel1.setBounds(20, 10, 300, 40);

        nameLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel3.setForeground(new java.awt.Color(255, 255, 0));
        TruthPanel.add(nameLabel3);
        nameLabel3.setBounds(310, 10, 160, 40);

        gameTruthButton.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        gameTruthButton.setForeground(new java.awt.Color(255, 0, 0));
        gameTruthButton.setText("Truth Game");
        gameTruthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameTruthButtonActionPerformed(evt);
            }
        });
        TruthPanel.add(gameTruthButton);
        gameTruthButton.setBounds(340, 600, 160, 40);

        jTextField4.setBackground(new java.awt.Color(51, 153, 255));
        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Try our truth tables game:");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        TruthPanel.add(jTextField4);
        jTextField4.setBounds(340, 550, 170, 30);

        pandqButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        pandqButton.setForeground(new java.awt.Color(255, 0, 0));
        pandqButton.setText("P and Q");
        pandqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pandqButtonActionPerformed(evt);
            }
        });
        TruthPanel.add(pandqButton);
        pandqButton.setBounds(40, 710, 130, 50);

        porqButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        porqButton.setForeground(new java.awt.Color(255, 0, 0));
        porqButton.setText("P or Q");
        porqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porqButtonActionPerformed(evt);
            }
        });
        TruthPanel.add(porqButton);
        porqButton.setBounds(190, 710, 130, 50);

        pnotqButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        pnotqButton.setForeground(new java.awt.Color(255, 0, 0));
        pnotqButton.setText("P not Q");
        pnotqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnotqButtonActionPerformed(evt);
            }
        });
        TruthPanel.add(pnotqButton);
        pnotqButton.setBounds(340, 710, 130, 50);

        jTextField3.setBackground(new java.awt.Color(51, 153, 255));
        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Online Resources:");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        TruthPanel.add(jTextField3);
        jTextField3.setBounds(340, 100, 130, 25);

        jTextField2.setBackground(new java.awt.Color(51, 153, 255));
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Here are some Truth Table examples:");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        TruthPanel.add(jTextField2);
        jTextField2.setBounds(140, 670, 260, 25);

        jList1.setBackground(new java.awt.Color(51, 153, 255));
        jList1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "www.Maths.com", "www.TruthTables.ie", "www.Logic.com", "www.NCIRL.ie" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        TruthPanel.add(jScrollPane3);
        jScrollPane3.setBounds(340, 140, 140, 100);

        BackgroundLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        TruthPanel.add(BackgroundLabel2);
        BackgroundLabel2.setBounds(-30, 0, 600, 770);

        ContentPanel.add(TruthPanel, "TruthCard");

        pandqPanel.setBackground(new java.awt.Color(255, 255, 255));
        pandqPanel.setLayout(null);

        PandQLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        PandQLabel.setText("P and Q");
        pandqPanel.add(PandQLabel);
        PandQLabel.setBounds(160, 90, 190, 80);

        nameLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel4.setForeground(new java.awt.Color(255, 255, 0));
        pandqPanel.add(nameLabel4);
        nameLabel4.setBounds(320, 10, 140, 40);

        learnLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        learnLabel2.setForeground(new java.awt.Color(255, 255, 0));
        learnLabel2.setText("Let's Learn Truth Tables");
        pandqPanel.add(learnLabel2);
        learnLabel2.setBounds(20, 10, 279, 40);

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel32.setText("Variables comes in two forms. They are either true or false.");
        pandqPanel.add(jLabel32);
        jLabel32.setBounds(50, 190, 410, 17);

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel33.setText("With that said, two variables must both be true if the result is to be true.");
        pandqPanel.add(jLabel33);
        jLabel33.setBounds(10, 220, 500, 17);

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel34.setText("For example, if both P and Q are true, then P and Q is true. ");
        pandqPanel.add(jLabel34);
        jLabel34.setBounds(50, 250, 400, 17);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Any other combination results in false.");
        pandqPanel.add(jLabel1);
        jLabel1.setBounds(110, 280, 280, 14);

        BackgroundLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/and table.jpg"))); // NOI18N
        BackgroundLabel3.setText("jLabel8");
        pandqPanel.add(BackgroundLabel3);
        BackgroundLabel3.setBounds(-30, 0, 580, 770);

        ContentPanel.add(pandqPanel, "pandqCard");

        porqPanel.setBackground(new java.awt.Color(255, 255, 255));
        porqPanel.setLayout(null);

        PorQLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        PorQLabel.setText("P or Q");
        porqPanel.add(PorQLabel);
        PorQLabel.setBounds(170, 110, 150, 51);

        nameLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel5.setForeground(new java.awt.Color(255, 255, 0));
        porqPanel.add(nameLabel5);
        nameLabel5.setBounds(320, 10, 140, 40);

        learnLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        learnLabel3.setForeground(new java.awt.Color(255, 255, 0));
        learnLabel3.setText("Let's Learn Truth Tables");
        porqPanel.add(learnLabel3);
        learnLabel3.setBounds(20, 10, 279, 40);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Variables come in two forms. They are either true or false.");
        porqPanel.add(jLabel8);
        jLabel8.setBounds(50, 200, 400, 14);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("If either one of the variables are True, then the result is True.");
        porqPanel.add(jLabel9);
        jLabel9.setBounds(40, 230, 440, 14);

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel23.setText("For example, P is True and Q is false, then P or Q is equal to True.");
        porqPanel.add(jLabel23);
        jLabel23.setBounds(30, 260, 450, 14);

        BackgroundLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/or gate.jpg"))); // NOI18N
        BackgroundLabel4.setText("jLabel14");
        porqPanel.add(BackgroundLabel4);
        BackgroundLabel4.setBounds(-30, 0, 620, 770);

        ContentPanel.add(porqPanel, "porqCard");

        pnotqPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnotqPanel.setLayout(null);

        PnotQLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        PnotQLabel.setText("P not Q");
        pnotqPanel.add(PnotQLabel);
        PnotQLabel.setBounds(170, 110, 140, 50);

        learnLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        learnLabel4.setForeground(new java.awt.Color(255, 255, 0));
        learnLabel4.setText("Let's Learn Truth Tables");
        pnotqPanel.add(learnLabel4);
        learnLabel4.setBounds(20, 10, 279, 40);

        nameLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel6.setForeground(new java.awt.Color(255, 255, 0));
        pnotqPanel.add(nameLabel6);
        nameLabel6.setBounds(320, 10, 170, 40);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Variables come in two forms. They are either true or false. ");
        pnotqPanel.add(jLabel2);
        jLabel2.setBounds(50, 200, 410, 21);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("If something is, 'not' a variable, then it is the ooposite of its original form.");
        pnotqPanel.add(jLabel4);
        jLabel4.setBounds(10, 230, 530, 21);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("For example, if P is True, then not P, is false.");
        pnotqPanel.add(jLabel6);
        jLabel6.setBounds(80, 260, 380, 30);

        BackgroundLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/not table.jpg"))); // NOI18N
        pnotqPanel.add(BackgroundLabel5);
        BackgroundLabel5.setBounds(-30, 0, 600, 770);

        ContentPanel.add(pnotqPanel, "pnotqCard");

        LeaderboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        LeaderboardPanel.setLayout(null);

        LeaderboardLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        LeaderboardLabel.setForeground(new java.awt.Color(255, 255, 0));
        LeaderboardLabel.setText("Welcome to Leaderboard");
        LeaderboardPanel.add(LeaderboardLabel);
        LeaderboardLabel.setBounds(30, 10, 287, 40);

        nameLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel7.setForeground(new java.awt.Color(255, 255, 0));
        LeaderboardPanel.add(nameLabel7);
        nameLabel7.setBounds(330, 10, 150, 40);

        jLabel11.setBackground(new java.awt.Color(51, 153, 255));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel11.setText("Top Scores");
        LeaderboardPanel.add(jLabel11);
        jLabel11.setBounds(60, 140, 197, 51);

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel49.setText("Position");
        LeaderboardPanel.add(jLabel49);
        jLabel49.setBounds(80, 240, 100, 26);

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel50.setText("Name");
        LeaderboardPanel.add(jLabel50);
        jLabel50.setBounds(220, 240, 70, 26);

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel51.setText("Score");
        LeaderboardPanel.add(jLabel51);
        jLabel51.setBounds(350, 240, 70, 26);

        jLabel52.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel52.setText("1st");
        LeaderboardPanel.add(jLabel52);
        jLabel52.setBounds(230, 300, 20, 21);

        jLabel59.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel59.setText("2nd");
        LeaderboardPanel.add(jLabel59);
        jLabel59.setBounds(230, 340, 24, 21);

        jLabel60.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel60.setText("3rd");
        LeaderboardPanel.add(jLabel60);
        jLabel60.setBounds(230, 380, 24, 21);

        jLabel61.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel61.setText("4th");
        LeaderboardPanel.add(jLabel61);
        jLabel61.setBounds(230, 420, 23, 21);

        jLabel62.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel62.setText("5th");
        LeaderboardPanel.add(jLabel62);
        jLabel62.setBounds(230, 460, 23, 21);

        jLabel63.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel63.setText("Arnis Lupiks");
        LeaderboardPanel.add(jLabel63);
        jLabel63.setBounds(70, 300, 79, 21);

        jLabel64.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel64.setText("Barry mc Gettigan");
        LeaderboardPanel.add(jLabel64);
        jLabel64.setBounds(70, 340, 120, 21);

        jLabel65.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel65.setText("Paul Cuffe");
        LeaderboardPanel.add(jLabel65);
        jLabel65.setBounds(70, 420, 66, 21);

        jLabel66.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel66.setText("Brian Wong");
        LeaderboardPanel.add(jLabel66);
        jLabel66.setBounds(70, 380, 73, 21);

        jLabel67.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel67.setText("Adam Wade");
        LeaderboardPanel.add(jLabel67);
        jLabel67.setBounds(70, 460, 76, 21);

        jLabel68.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel68.setText("100");
        LeaderboardPanel.add(jLabel68);
        jLabel68.setBounds(370, 300, 24, 21);

        jLabel69.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel69.setText("80");
        LeaderboardPanel.add(jLabel69);
        jLabel69.setBounds(370, 340, 18, 21);

        jLabel70.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel70.setText("60");
        LeaderboardPanel.add(jLabel70);
        jLabel70.setBounds(370, 380, 18, 21);

        jLabel71.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel71.setText("40");
        LeaderboardPanel.add(jLabel71);
        jLabel71.setBounds(370, 420, 18, 21);

        jLabel72.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel72.setText("20");
        LeaderboardPanel.add(jLabel72);
        jLabel72.setBounds(370, 460, 18, 21);
        LeaderboardPanel.add(jLabel73);
        jLabel73.setBounds(0, 0, 0, 0);

        BackgroundLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LearningApp/Untitled-2.jpg"))); // NOI18N
        LeaderboardPanel.add(BackgroundLabel6);
        BackgroundLabel6.setBounds(-20, 0, 610, 770);

        ContentPanel.add(LeaderboardPanel, "LeaderboardCard");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ButtonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .add(ContentPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(ContentPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ButtonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void learnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "LearnCard");
        addToPanelStack("LearnCard"); 
        
         TextToSpeech speech = TextToSpeechFactory.getDefaultTextToSpeech();
         speech.speakBlocking("Let's learn");
   }//GEN-LAST:event_learnButtonActionPerformed

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "GameCard");
        addToPanelStack("GameCard");
         
        TextToSpeech speech = TextToSpeechFactory.getDefaultTextToSpeech();
         speech.speakBlocking("Let's play the game");
    }//GEN-LAST:event_gameButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "HomeCard");
        addToPanelStack("HomeCard");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        if (!PanelStack.isEmpty()) {
            cl.show(ContentPanel, previousPanel());
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //Arnis Lupiks
        enterNameField.setText(" ");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
           //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "HomeCard");
        if (!enterNameField.getText().equals("Enter your Name?")) {
            nameLabel.setText(enterNameField.getText());
            nameLabel2.setText(enterNameField.getText());
            nameLabel3.setText(enterNameField.getText());
            nameLabel4.setText(enterNameField.getText());
            nameLabel5.setText(enterNameField.getText());
            nameLabel6.setText(enterNameField.getText());
            nameLabel7.setText(enterNameField.getText());
            nameLabel8.setText(enterNameField.getText());
            nameLabel9.setText(enterNameField.getText());
            nameLabel10.setText(enterNameField.getText());
          }
      TextToSpeech speech = TextToSpeechFactory.getDefaultTextToSpeech();
           speech.speakBlocking("Welcome, please select on the botton panel one of the options");
       
           
         
     
    }//GEN-LAST:event_submitButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
         System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void enterNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterNameFieldActionPerformed
        //name = enterNameField.setName();
        //this.name = name;
         
    }//GEN-LAST:event_enterNameFieldActionPerformed

    private void pandqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pandqButtonActionPerformed
        //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "pandqCard");
        addToPanelStack("pandqCard");
    }//GEN-LAST:event_pandqButtonActionPerformed

    private void truthTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truthTableButtonActionPerformed
        //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "TruthCard");
        addToPanelStack("TruthCard");
    }//GEN-LAST:event_truthTableButtonActionPerformed

    private void porqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porqButtonActionPerformed
        //Arnis Lupiks used the code from example which was given    
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "porqCard");
        addToPanelStack("porqCard");
    }//GEN-LAST:event_porqButtonActionPerformed

    private void pnotqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnotqButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "pnotqCard");
        addToPanelStack("pnotqCard");
    }//GEN-LAST:event_pnotqButtonActionPerformed

    private void TruthGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruthGameButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "truthGameCard");
        addToPanelStack("truthGameCard");
    }//GEN-LAST:event_TruthGameButtonActionPerformed

    private void D8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D8ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_D8ActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed
        // Brian Wong
        
        String ans1, ans2, ans3, ans4, ans5;
        
        ans1=D8.getText();
        ans2=AD7.getText();
        ans3=AC3.getText();
        ans4=DorAC5.getText();
        ans5=ADandDorAC7.getText();
        
        if (ans1.equals("T") ||ans1.equals("t")){
            
            score ++;
            
        }
        
        if (ans2.equals("F") ||ans2.equals("f")) {
            score ++;
        }
        
        if (ans3.equals("F") ||ans3.equals("f")) {
            score ++;
        }
        
        if (ans4.equals("F") ||ans4.equals("f")) {
            score ++;
        }
        
        if (ans5.equals("F") ||ans5.equals("f")) {
            score ++;
        }
        
        if (score == (5)) {
            ResultsBox.setText("You win!");
        }
        
        if (score == (4)) {
            ResultsBox.setText("Almost! You got 4 out of 5 right!");
        }
        
        if (score == (3)) {
            ResultsBox.setText("Not bad. You got 3 out of 5.");
        }
        
        if (score == (2)) {
            ResultsBox.setText("Pretty bad. You got 2 out of 5.");
        }
        
        if (score == (1)) {
            ResultsBox.setText("You didn't do very well. You only got 1 out of 5.");
        }
        
        if (score == (0)) {
            ResultsBox.setText("Awful. You didn't get a single one right.");
        }
        
        
    }//GEN-LAST:event_SubmitbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Brian Wong
        
        D8.setText("");
        AD7.setText("");
        AC3.setText("");
        DorAC5.setText("");
        ADandDorAC7.setText("");
        ResultsBox.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

    private void LogicGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogicGameButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "logicGameCard");
        addToPanelStack("logicGameCard");
        
        
        
    }//GEN-LAST:event_LogicGameButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void gameTruthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameTruthButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "truthGameCard");
        addToPanelStack("truthGameCard");
    }//GEN-LAST:event_gameTruthButtonActionPerformed

    private void LeaderboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaderboardButtonActionPerformed
        // Barry mc Gettigan
        ArrayList <Player> playerList = new ArrayList();
        
        Player player1 = new Player();
        player1.setFirstName("Arnis");
        player1.setLastName("Lupiks");
        player1.setScore(100);
        
        playerList.add(player1);
        
        Player player2 = new Player();
        player2.setFirstName("Barry");
        player2.setLastName("Mc Gettigan");
        player2.setScore(80);
        
        playerList.add(player2);
        
        Player player3 = new Player();
        player3.setFirstName("Paul");
        player3.setLastName("Cuffe");
        player3.setScore(60);
        
        playerList.add(player3);
        
        Player player4 = new Player();
        player4.setFirstName("Brian");
        player4.setLastName("Wong");
        player4.setScore(40);
        
        playerList.add(player4);
        
        Player player5 = new Player();
        player5.setFirstName("Adam");
        player5.setLastName("Wade");
        player5.setScore(20);
        
        playerList.add(player5);
        
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "LeaderboardCard");
        addToPanelStack("LeaderboardCard");
        
        for (int i=0; i<playerList.size(); i++){
            Player p = new Player();
            p = playerList.get(i);
            JOptionPane.showMessageDialog(null,(i+1)+ " Position = " + p.getFirstName() + " " +  p.getLastName() + ", score is " +  p.getScore() );
        }
}//GEN-LAST:event_LeaderboardButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "logicGameCard");
        addToPanelStack("logicGameCard");
}//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        
}//GEN-LAST:event_jTextField6ActionPerformed

    private void logicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicButtonActionPerformed
         //Arnis Lupiks used the code from example which was given
        CardLayout cl = (CardLayout) (ContentPanel.getLayout());
        cl.show(ContentPanel, "logicCard");
        addToPanelStack("logicCard");
    }//GEN-LAST:event_logicButtonActionPerformed

    private void addToPanelStack(String card){
        if(PanelStack.isEmpty()){
          PanelStack.push(card); 
        } else {
            if(!PanelStack.peek().equals(card)){
               PanelStack.push(card);
            }              
        }
    }
    
    private String previousPanel(){
        if(!PanelStack.empty()){
            PanelStack.pop();
            if(!PanelStack.empty()){
                return PanelStack.peek().toString();
            }else {
                return "HomeCard";
            }   
        } else {
            return "HomeCard";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        //Arnis Lupiks find this code in web
    TextToSpeech speech = TextToSpeechFactory.getDefaultTextToSpeech();
             
         if (args.length == 0)
        {
            speech.speakBlocking(introText);
        }
        else
        {
            speech.speakBlocking(args[0]);
        }
        
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    Stack PanelStack=new Stack();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AC3;
    private javax.swing.JTextField AD7;
    private javax.swing.JTextField ADandDorAC7;
    private javax.swing.JLabel AboutUs;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel BackgroundLabel10;
    private javax.swing.JLabel BackgroundLabel2;
    private javax.swing.JLabel BackgroundLabel3;
    private javax.swing.JLabel BackgroundLabel4;
    private javax.swing.JLabel BackgroundLabel5;
    private javax.swing.JLabel BackgroundLabel6;
    private javax.swing.JLabel BackgroundLabel7;
    private javax.swing.JLabel BackgroundLabel8;
    private javax.swing.JLabel BackgroundLabel9;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JTextField D8;
    private javax.swing.JTextField DorAC5;
    private javax.swing.JLabel Game1Label;
    private javax.swing.JLabel GameLabel;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton LeaderboardButton;
    private javax.swing.JLabel LeaderboardLabel;
    private javax.swing.JPanel LeaderboardPanel;
    private javax.swing.JLabel LogicBackground;
    private javax.swing.JButton LogicGameButton;
    private javax.swing.JPanel LogicPanel;
    private javax.swing.JLabel PandQLabel;
    private javax.swing.JLabel PnotQLabel;
    private javax.swing.JLabel PorQLabel;
    private javax.swing.JLabel ResultsBox;
    private javax.swing.JButton Submitbtn;
    private javax.swing.JButton TruthGameButton;
    private javax.swing.JPanel TruthPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField enterNameField;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JButton gameButton;
    private javax.swing.JButton gameTruthButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton learnButton;
    private javax.swing.JLabel learnLabel;
    private javax.swing.JLabel learnLabel1;
    private javax.swing.JLabel learnLabel2;
    private javax.swing.JLabel learnLabel3;
    private javax.swing.JLabel learnLabel4;
    private javax.swing.JLabel learnLabel5;
    private javax.swing.JPanel learnPanel;
    private javax.swing.JButton logicButton;
    private javax.swing.JPanel logicGamePanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel10;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel nameLabel6;
    private javax.swing.JLabel nameLabel7;
    private javax.swing.JLabel nameLabel8;
    private javax.swing.JLabel nameLabel9;
    private javax.swing.JButton pandqButton;
    private javax.swing.JPanel pandqPanel;
    private javax.swing.JButton pnotqButton;
    private javax.swing.JPanel pnotqPanel;
    private javax.swing.JButton porqButton;
    private javax.swing.JPanel porqPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel truthGameLabel;
    private javax.swing.JPanel truthGamePanel;
    private javax.swing.JButton truthTableButton;
    // End of variables declaration//GEN-END:variables
}
